global:
  scrape_interval: 10s 

scrape_configs:
- job_name: kafka
  static_configs:
          - targets: ['kafka:7071']

- job_name: myapp
  scrape_interval: 10s
  static_configs:
  - targets:
    - 9.134.50.24:2112
